### PR TITLE
[DO NOT MERGE] Build gem with GitHub Actions

### PR DESCRIPTION
**Pull request by ChrisBAshton**
Takes inspiration from https://github.com/alphagov/rubocop-govuk/pull/45
I've saved the API credential under 'Secrets' in this repo, as
'GEM_HOST_API_KEY', which is referenced by the GitHub Action.

The logic is conditional so that a gem is only built and published
if the version doesn't match the latest version on rubygems.
As we haven't been able to release 0.11.1 yet, this should mean
that gem is released when this PR is merged.

### CODE REVIEW

**Comment by ChrisBAshton** [comment]
Hi @MatMoore - we're planning to use GitHub Actions to publish this gem, following [the approach taken in other GOV.UK repositories](https://github.com/alphagov/rubocop-govuk/pull/45). We've just noticed [middleman-search-gds is under your ownership](https://rubygems.org/profiles/MatMoore), so our publish action is unlikely to work.

Would you mind transferring ownership of this gem to GOV.UK? I think this is the command to use: `gem owner middleman-search-gds -a govuk-dev@digital.cabinet-office.gov.uk`

**Comment by MatMoore** [comment]
Sorry @ChrisBAshton, I don't have access to that account anymore. 😞

It belongs to my cabinet office email address, which I no longer control.

I suggest contacting RubyGems directly and see if they can help you take over the account. Sorry for the inconvenience. At the time we forked this, the tech docs gem wasn't owned by GOV.UK, and I don't think there was a GDS shared account, so that might be why I published it seperately (and then forgot about it).

**Comment by ChrisBAshton** [comment]
Thanks @MatMoore. I have raised a support ticket with them.

Adding `DO NOT MERGE` label to this PR, in favour of #7 for the time being.

**Comment by thomasleese** [comment]
I think we can probably close this for now since we're going to use Jenkins. We can always re-open it if we need to.

**Pull request closed without merging**
